apiVersion: v2
name: training-operators
version: 0.1.0
appVersion: v1.7.0
description: A Helm chart for deploying Kubeflow Training Operators
keywords:
  - kubeflow
  - training
  - operators
  - pytorchjob