apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: {{ .Values.namePrefix }}controller-manager
    app.kubernetes.io/name: {{ .Values.namePrefix }}App
  name: {{ .Values.namePrefix }}controller-manager-metrics-service
  namespace: {{ .Values.namePrefix }}system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: {{ .Values.namePrefix }}controller-manager
