apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.namePrefix }}
  name: {{ .Values.namePrefix }}-leader-election-rolebinding
  namespace: {{ .Values.shortPrefix }}-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.namePrefix }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.namePrefix }}-controller-manager
  namespace: {{ .Values.shortPrefix }}-system
