{{- if false }} # Role is still in development
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.namePrefix }}-metrics-auth-rolebinding
  namespace: {{ .Values.shortPrefix }}-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.namePrefix }}-controller-manager
  namespace: {{ .Values.shortPrefix }}-system
{{- end }}
