---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deploymentoperator
  name: {{ .Values.namePrefix }}manager-role
  namespace: {{ .Values.namePrefix }}system
rules:
- apiGroups:
  - inference.sagemaker.aws.amazon.com
  resources:
  - bedrockendpointregistrations
  - jumpstartmodels
  - inferenceendpointconfigs
  - sagemakerendpointregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inference.sagemaker.aws.amazon.com
  resources:
  - bedrockendpointregistrations/finalizers
  - jumpstartmodels/finalizers
  - inferenceendpointconfigs/finalizers
  - sagemakerendpointregistrations/finalizers
  verbs:
  - update
- apiGroups:
  - inference.sagemaker.aws.amazon.com
  resources:
  - bedrockendpointregistrations/status
  - jumpstartmodels/status
  - inferenceendpointconfigs/status
  - sagemakerendpointregistrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  - apps
  - batch
  - networking.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
    - kueue.x-k8s.io
  resources:
    - clusterqueues
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - kueue.x-k8s.io
  resources:
    - clusterqueues/finalizers
  verbs:
    - update
- apiGroups:
    - kueue.x-k8s.io
  resources:
    - clusterqueues/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
  - cert-manager.io
  resources:
    - issuers 
    - secrets
    - certificates 
  verbs:
    - get
    - list
    - watch
    - create
    - delete