apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.namePrefix }}
  name: {{ .Values.namePrefix }}-manager-rolebinding
  namespace: {{ .Values.shortPrefix }}-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.namePrefix }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.namePrefix }}-controller-manager
  namespace: {{ .Values.shortPrefix }}-system
