apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.namePrefix }}
  name: {{ .Values.namePrefix }}-controller-manager
  namespace: {{ .Values.shortPrefix }}-system
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.executionRoleArn }}
