defaults:
 - override hydra/job_logging: stdout

hydra:
 run:
  dir: .
 output_subdir: null

training_cfg:
 entry_script: /workspace/train.py # Path to the entry script of training/fine-tuning, when running k8s, this path should be inside container
 script_args: []
 run:
  name: test-custom # Current run name
  nodes: 2 # Number of nodes to use for current training
  # ntasks_per_node: 1 # Number of devices to use per node
cluster:
 cluster_type: k8s # currently k8s only
 instance_type: c5.2xlarge
 cluster_config:
  # persistent volume, usually used to mount FSx
  persistentVolumeClaim:
   # This claim should be created before running
   claimName: null
   mountPath: null
  namespace: kubeflow
  # required node affinity to select nodes with HyperPod
  # labels and passed health check if burn-in enabled
  label_selector:
      required:
          sagemaker.amazonaws.com/node-health-status:
              - Schedulable
      preferred:
          sagemaker.amazonaws.com/deep-health-check-status:
              - Passed
      weights:
          - 100
  pullPolicy: Always # policy to pull container, can be Always, IfNotPresent and Never
  restartPolicy: OnFailure # restart policy

base_results_dir: ./result # Location to store the results, checkpoints and logs.
container: docker.io/kubeflowkatib/pytorch-mnist:v1beta1-45c5727 # container to use

env_vars:
 NCCL_DEBUG: INFO # Logging level for NCCL. Set to "INFO" for debug information