from pydantic import BaseModel, Field
from typing import Optional, Literal, List, Any

class ClusterStackBase(BaseModel):
    stage: Optional[str] = Field(None, description="Deployment stage (gamma, prod)")
    enable_hp_inference_feature: Optional[str] = Field(None, description="Feature flag for enabling HP inference")
    custom_bucket_name: Optional[str] = Field(None, description="Custom S3 bucket name for templates")
    resource_name_prefix: Optional[str] = Field(None, description="Prefix to be used for all resources")
    vpc_cidr: Optional[str] = Field(None, description="The IP range (CIDR notation) for the VPC")
    availability_zone_ids: Optional[str] = Field(None, description="List of AZs to deploy subnets in")
    vpc_id: Optional[str] = Field(None, description="The ID of the VPC")
    nat_gateway_ids: Optional[str] = Field(None, description="Comma-separated list of NAT Gateway IDs")
    security_group_id: Optional[str] = Field(None, description="The ID of the security group")
    kubernetes_version: Optional[str] = Field(None, description="The Kubernetes version")
    node_provisioning_mode: Optional[str] = Field(None, description="The node provisioning mode")
    eks_cluster_name: Optional[str] = Field(None, description="The name of the EKS cluster")
    eks_private_subnet_ids: Optional[str] = Field(None, description="Comma-delimited list of private subnet IDs")
    security_group_ids: Optional[str] = Field(None, description="The Id of your cluster security group")
    private_route_table_ids: Optional[str] = Field(None, description="Comma-separated list of private route table IDs")
    s3_bucket_name: Optional[str] = Field(None, description="The name of the S3 bucket")
    github_raw_url: Optional[str] = Field(None, description="The raw GitHub URL for the lifecycle script")
    helm_repo_url: Optional[str] = Field(None, description="The URL of the Helm repo")
    helm_repo_path: Optional[str] = Field(None, description="The path to the HyperPod Helm chart")
    helm_operators: Optional[str] = Field(None, description="The configuration of HyperPod Helm chart")
    namespace: Optional[str] = Field(None, description="The namespace to deploy the HyperPod Helm chart")
    helm_release: Optional[str] = Field(None, description="The name of the Helm release")
    hyperpod_cluster_name: Optional[str] = Field(None, description="Name of SageMaker HyperPod Cluster")
    node_recovery: Optional[str] = Field(None, description="Instance recovery setting")
    sagemaker_iam_role_name: Optional[str] = Field(None, description="The name of the IAM role")
    private_subnet_ids: Optional[str] = Field(None, description="Comma-separated list of private subnet IDs")
    on_create_path: Optional[str] = Field(None, description="The file name of lifecycle script")
    instance_group_settings: Optional[str] = Field(None, description="JSON array string containing instance group configurations")
    rig_settings: Optional[str] = Field(None, description="JSON array string containing restricted instance group configurations")
    rig_s3_bucket_name: Optional[str] = Field(None, description="The name of the S3 bucket for RIG resources")
    tags: Optional[str] = Field(None, description="Custom tags for managing the SageMaker HyperPod cluster")
    fsx_subnet_id: Optional[str] = Field(None, description="The subnet id for FSx")
    fsx_availability_zone_id: Optional[str] = Field(None, description="The availability zone for FSx")
    per_unit_storage_throughput: Optional[int] = Field(None, description="Per unit storage throughput")
    data_compression_type: Optional[str] = Field(None, description="Data compression type")
    file_system_type_version: Optional[float] = Field(None, description="File system type version")
    storage_capacity: Optional[int] = Field(None, description="Storage capacity in GiB")
    fsx_file_system_id: Optional[str] = Field(None, description="Existing FSx file system ID")
    create_vpc_stack: Optional[bool] = Field(None, description="Boolean to Create VPC Stack")
    create_security_group_stack: Optional[bool] = Field(None, description="Boolean to Create Security Group Stack")
    create_eks_cluster_stack: Optional[bool] = Field(None, description="Boolean to Create EKS Cluster Stack")
    create_s3_bucket_stack: Optional[bool] = Field(None, description="Boolean to Create S3 Bucket Stack")
    create_s3_endpoint_stack: Optional[bool] = Field(None, description="Boolean to Create S3 Endpoint Stack")
    create_life_cycle_script_stack: Optional[bool] = Field(None, description="Boolean to Create Life Cycle Script Stack")
    create_sagemaker_iam_role_stack: Optional[bool] = Field(None, description="Boolean to Create SageMaker IAM Role Stack")
    create_helm_chart_stack: Optional[bool] = Field(None, description="Boolean to Create Helm Chart Stack")
    create_hyperpod_cluster_stack: Optional[bool] = Field(None, description="Boolean to Create HyperPod Cluster Stack")
    create_fsx_stack: Optional[bool] = Field(None, description="Boolean to Create FSx Stack")
