{{- range .Values.priorityClasses }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .name }}
value: {{ .value }}
preemptionPolicy: {{ .preemptionPolicy | default "PreemptLowerPriority" }}
globalDefault: {{ .globalDefault | default false }}
description: "{{ .description }}"
{{- end }}