{{- if .Values.createNamespace -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    sagemaker.amazonaws.com/sagemaker-managed-queue: "true"
    sagemaker.amazonaws.com/quota-allocation-id: IML-Team-A
    sagemaker.amazonaws.com/activate-quota: Enabled
{{- end -}}