name: Python Unit Test CI After Commit

on:
  push:
    branches:
      - main # Triggers on direct pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive # Checkout submodules as well

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # Set python version to 3.8

      - name: Install unit test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r launcher/nemo/nemo_framework_launcher/requirements.txt
          pip install pytest
          pip install pytest-cov

      - name: Run unit tests
        run: |
          python -m pytest
