# Original Copyright (c), NVIDIA CORPORATION. Modifications © Amazon.com

run:
  name: mixtral
  results_dir: ${base_results_dir}/${.name}
  time_limit: "6-00:00:00"
  model_type: hf # huggingface for our recipes


trainer:
  devices: 8
  num_nodes: 32
  accelerator: gpu
  precision: bf16
  max_steps: 50
  log_every_n_steps: 1
  val_check_interval: 1
  limit_val_batches: 0 # Number of batches per each validation run, set to 0 to disable validation.


exp_manager:
  exp_dir: null
  name: experiment
  # experiment loggers
  create_tensorboard_logger: False
  summary_writer_kwargs: {"save_dir" : "${recipes.exp_manager.exp_dir}/tensorboard"}
  create_mlflow_logger: False
  mlflow_logger_kwargs: {"tracking_uri" : "${recipes.exp_manager.exp_dir}/mlflow"}
  create_wandb_logger: False
  wandb_logger_kwargs: {"save_dir" : "${recipes.exp_manager.exp_dir}"} # wandb creates a wandb folder by default
  create_checkpoint_callback: False
  checkpoint_callback_params:
    # Set save_top_k = 0 to disable sharded checkpointing
    save_top_k: 0
    every_n_train_steps: 10
    monitor: "step"
    mode: "max"
    save_last: False
  checkpoint_dir: ${recipes.exp_manager.exp_dir}/checkpoints/
  resume_from_checkpoint: null
  # Set auto_checkpoint = False to disable auto resilience checkpointing
  auto_checkpoint:
    enabled: False
  export_full_model:
    # Set every_n_train_steps = 0 to disable full checkpointing
    every_n_train_steps: 0
    save_last: True

use_smp_model: True # Enable sagemaker model parallelism
distributed_backend: nccl

# Start training from pretrained model
model:
  model_type: mixtral

  train_batch_size: 2
  val_batch_size: 1
  tensor_model_parallel_degree: 1
  expert_model_parallel_degree: 1
  moe: True
  activation_checkpointing: True
  activation_loading_horizon: 2
  delayed_param: True
  offload_activations: False
  seed: 12345
  grad_clip: 1.0


  # FSDP Configs
  sharding_strategy: full_shard
  forward_prefetch: True
  shard_degree: 128
  backward_fetch_policy: backward_pre
  auto_wrap_policy: transformer_auto_wrap_policy
  limit_all_gathers: true
  use_orig_param: True

  # model architecture
  max_context_width: 16384
  max_position_embeddings: ${.max_context_width}
  num_hidden_layers: 32
  hidden_size: 4096
  num_attention_heads: 32
  intermediate_size: 14336
  initializer_range: 0.02
  layernorm_epsilon: 1e-5
  vocab_size: 32000
  num_key_value_heads: 8
  use_flash_attention: True
  sliding_window: null
  num_experts_per_tok: 2
  num_local_experts: 8
  moe_load_balancing: 'sinkhorn'
  global_token_shuffle: True
  moe_all_to_all_dispatcher: False
  rope_theta: 1000000.0

  # Transformer Engine
  fp8: False
  fp8_amax_history_len: 1024
  fp8_amax_compute_algo: max

  # finetune
  do_finetune: False
  # smp calls it `pretrained_model_weights` but we opted to follow the name used by HF
  hf_model_name_or_path: null

  precision: ${recipes.trainer.precision}

  lr_decay_iters: ${recipes.trainer.max_steps}

  log_reduced_training_loss: True

  # Optimizer
  optim:
    name: adamw
    lr: 0.0001
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.95
    sched:
      name: CosineAnnealing
      warmup_steps: 0
      constant_steps: 0
      min_lr: 0.000001



  # Data
  data:
    train_dir: null
    val_dir: null
    dataset_type: hf
    use_synthetic_data: False

  # Viztracer
  viztracer:
    enabled: false
