DEFAULT_REPLICAS = 1
DEFAULT_MAX_DEPLOY_TIME_IN_SECONDS = 3600
DEFAULT_MODEL_METRIC_PATH = "/metrics"
DEFAULT_METRICS_SCRAPE_INTERBAL_SECONDS = 15
INFERENCE_FULL_API_VERSION = "inference.sagemaker.aws.amazon.com/v1alpha1"
INFERENCE_GROUP = "inference.sagemaker.aws.amazon.com"
INFERENCE_API_VERSION = "v1alpha1"
JUMPSTART_MODEL_KIND = "JumpStartModel"
JUMPSTART_MODEL_PLURAL = "jumpstartmodels"
INFERENCE_ENDPOINT_CONFIG_KIND = "InferenceEndpointConfig"
INFERENCE_ENDPOINT_CONFIG_PLURAL = "inferenceendpointconfigs"
DEFAULT_MOUNT_PATH = "/opt/ml/model"
OPERATOR_NAMESPACE = "hyperpod-inference-system"

KIND_PLURAL_MAP = {
    JUMPSTART_MODEL_KIND: JUMPSTART_MODEL_PLURAL,
    INFERENCE_ENDPOINT_CONFIG_KIND: INFERENCE_ENDPOINT_CONFIG_PLURAL,
}
