default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
      exclude: ^(tests/slurm_workflow/slurm_baseline_artifacts/|tests/k8s_workflow/k8s_baseline_artifacts/|tests/sm_jobs_workflow/sm_jobs_baseline_artifacts/)
    - id: trailing-whitespace
      exclude: ^(tests/slurm_workflow/slurm_baseline_artifacts/|tests/k8s_workflow/k8s_baseline_artifacts/|tests/sm_jobs_workflow/sm_jobs_baseline_artifacts/)
- repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.3
  hooks:
    - id: autoflake
      args: ['--in-place', '--expand-star-imports', '--ignore-init-module-imports', '--remove-all-unused-imports']
      additional_dependencies: [setuptools]
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      args: [--line-length=120]
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.1.1
  hooks:
    - id: clang-format
      args: [--style=file, -i]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks: # imports sorting
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]
