priorityClasses:
  - name: priority3
    namespace: "kubeflow"
    value: 1000
    globalDefault: false
    description: "High priority class with preemption"
  - name: priority4
    namespace: "kubeflow"
    value: 100
    globalDefault: false
    description: "Low priority class without preemption"

clusterQueue:
  name: "cluster-queue1"
  namespaceSelector: {}

queues:
  - name: high-priority-queue2
    namespace: "kubeflow"
  - name: low-priority-queue2
    namespace: "kubeflow"