name: "Code Coverage"
on: 
  pull_request:
    branches: [ "main", "master" ]

jobs:
  coverage:
    name: Overall Coverage Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions: 
      contents: read
      pull-requests: write
    
    strategy:
      matrix: 
        python-version: ["3.11"]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install project dependencies first
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f setup.py ]; then pip install -e .; fi
          # Install testing tools
          pip install pytest pytest-cov
      
      - name: Run Unit Tests with Coverage
        run: |
          pytest test/unit_tests/ --cov=src/ --cov-report=term-missing --cov-report=xml:coverage.xml --cov-fail-under=70
      
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage.xml
