apiVersion: inference.sagemaker.aws.amazon.com/v1
kind: InferenceEndpointConfig
metadata:
  name: demo-l1-l2-membrain-with-ir
  namespace: ns-team-a
spec:
  modelName: Llama-3.1-8B-Instruct
  instanceType: ml.p5.48xlarge
  invocationEndpoint: v1/chat/completions
  replicas: 7
  modelSourceConfig:
    modelSourceType: s3
    s3Storage:
      bucketName: <YOUR_MODEL_BUCKET>
      region: us-east-2
    modelLocation: models/Llama-3.1-70B-Instruct
    prefetchEnabled: false
  kvCacheSpec:
    enableL1Cache: true
    enableL2Cache: true
    l2CacheSpec:
      l2CacheBackend: tieredstorage
  intelligentRoutingSpec:
    enabled: true
    routingStrategy: prefixaware
  tlsConfig:
    tlsCertificateOutputS3Uri: s3://<YOUR_TLS_BUCKET>/certificates
  metrics:
    enabled: true
    modelMetrics:
      port: 8000
  loadBalancer:
    healthCheckPath: /health
  worker:
    resources:
      limits:
        nvidia.com/gpu: "8"
        cpu: "48"
        memory: 100Gi
      requests:
        cpu: "48"
        memory: 512Gi
        nvidia.com/gpu: "4"
    image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/<YOUR_LMCACHE_IMAGE>
    args:
      - "/opt/ml/model"
      - "--max-model-len"
      - "12000"
    modelInvocationPort:
      containerPort: 8000
      name: http
    modelVolumeMount:
      name: model-weights
      mountPath: /opt/ml/model
    environmentVariables:
      - name: PYTHONHASHSEED
        value: "123"
      - name: OPTION_ROLLING_BATCH
        value: "vllm"
      - name: SERVING_CHUNKED_READ_TIMEOUT
        value: "480"
      - name: DJL_OFFLINE
        value: "true"
      - name: NUM_SHARD
        value: "1"
      - name: SAGEMAKER_PROGRAM
        value: "inference.py"
      - name: SAGEMAKER_SUBMIT_DIRECTORY
        value: "/opt/ml/model/code"
      - name: MODEL_CACHE_ROOT
        value: "/opt/ml/model"
      - name: SAGEMAKER_MODEL_SERVER_WORKERS
        value: "1"
      - name: SAGEMAKER_MODEL_SERVER_TIMEOUT
        value: "3600"
      - name: OPTION_TRUST_REMOTE_CODE
        value: "true"
      - name: OPTION_ENABLE_REASONING
        value: "true"
      - name: OPTION_REASONING_PARSER
        value: "deepseek_r1"
      - name: SAGEMAKER_CONTAINER_LOG_LEVEL
        value: "20"
      - name: SAGEMAKER_ENV
        value: "1"