apiVersion: inference.sagemaker.aws.amazon.com/v1alpha1
kind: ModelDeployment
metadata:
  labels:
    app.kubernetes.io/name: huggingface-llm-mistral-7b-instruct-app
    kueue.x-k8s.io/priority-class: real-time-inference
  name: sample-mistral
  namespace: ns-team-a
spec:
  sageMakerEndpoint:
    name: sample-sagemaker-endpoint
  model:
    acceptEula: true
    modelHubName: SageMakerPublicHub
    modelId: huggingface-llm-mistral-7b-instruct
  server:
    instanceType: ml.g5.8xlarge
    maxAutoScaleReplicas: 2
    minAutoScaleReplicas: 1
    namespace: inference-namespace
  environmentVariables:
    - name: SAMPLE_ENV_VAR
      value: "sample_value"
  maxDeployTimeInSeconds: 1800